### ISSUE TITLE
Whisper and gpt2

### ISSUE THREAD

**Issue by basecl** [BriansIDP/WhisperBiasing#10]
How come we use whisper tokenizer (I mean multilingual version) and then feed it into gpt2? There are different tokenizers in gpt2, or in the process of fine tune gpt2 adapts to them ?

**Comment by BriansIDP** [comment]
The GPT-2 in the paper is only used to do rescore which is an N-best rescore so whatever tokenizer we use, it does not matter. The entire training and decoding is using whisper tokenizer.
