### ISSUE TITLE
dev_error.json

### ISSUE THREAD

**Issue by bkiefer** [BriansIDP/WhisperBiasing#7]
I hope this is not a completely stupid issue, but using LibriSpeech and train_large.sh as described in the ReadMe, it breaks with the error that it can not load data/LibriSpeech/dev_error.json, which is obviously not present, and there is no description what to use to replicate the results.

**Comment by BriansIDP** [comment]
Hi. Thanks for the question. 
Please follow the data preparation instructions to generate dev_error.json: You need to run `get_rarewords.py` with `rareword_error.txt` and data for dev set to generate dev_error.json.

**Comment by bkiefer** [comment]
Hi, thanks for the instructions!
