### ISSUE TITLE
Unable to reproduce results in paper

### ISSUE THREAD

**Issue by cyaaronk** [BriansIDP/WhisperBiasing#8]
Dear Author,

I followed the exact code to train and test Whisper large + TCPGen, but I cannot achieve the results described in the paper.
Whisper large + TCPGen test-clean results:
Paper: WER 3.4% and R-WER 8.3%
Mine: WER 3.8% and R-WER 9.4%

The only change is that I use a beam size of 30 instead of 50 as I got GPU out of memory error. But I observe that changing the beam size only affect the WER by about absolute 0.1%. This shows that my model accuracy will be far from the 3.4% in the paper even if I use beam size of 50.

So may I know the hyperparameters you used for the experiments? I have made a copy of my hyperparameters as below, but they should not be different from the one in you repo except for the beam size.

Thank you.

The hyperparams for training:
python -u train.py \
    --modeltype large \
    --train_json data/LibriSpeech/train_clean_100_error.json \
    --dev_json data/LibriSpeech/dev_error.json \
    --lr 0.0005 \
    --batch_size 8 \
    --log_interval 200 \
    --nepochs 30 \
    --warmup_pct 0.0 \
    --decay_pct 0.2 \
    --expdir exp/${expdir} \
    --logfile exp/${expdir}/log.txt \
    --accumgrad 10 \
    --biasing \
    --biasinglist data/LibriSpeech/Blist/rareword_error.txt \
    --dropentry 0.3 \
    --maxKBlen 100 \

The hyperparams for testing:
python -u decode.py \
    --test_json data/LibriSpeech/test_${testset}_full.json \
    --beamsize $10 \
    --expdir $expdir/$decodedir \
    --loadfrom $expdir/model.acc.best \
    --biasing \
    --biasinglist data/LibriSpeech/Blist/all_rare_words.txt \
    --dropentry 0.0 \
    --maxKBlen 1000 \
    --save_nbest \

**Comment by BriansIDP** [comment]
Hi. Thanks for the message. 

The default download is large-v2 for whisper whereas the set of hyper-parameters were optimised for whisper large. I wonder if you can check whether that is the case. We did not have access to large-v2 when experiments were carried out in this paper. Please feel free to adjust the hyper-parameters as you need, such as `--dropentry` and `--maxKBlen` for training. Please also observe the loss and the P_gen value to see if that is normal (i.e. P_gen should be high when biasing is needed).

Sorry for the inconvenience.

**Comment by cyaaronk** [comment]
Thank you for your help! I will test with large instead of large-v2 to see if it is the case

**Comment by BriansIDP** [comment]
Hi,

So even if you choose --modeltype large, the current openAI code will automatically download whisper.large-v2. Please double-check if the checkpoint you downloaded is large or large-v2.

Yes please monitor the max value of gen_prob during inference.

That's the only hyper-parameters that I might tune for a different foundation model. If you observe the max gen_prob to be too small, i.e. the model is not using the biasing information, you might consider decreasing the dropentry or decreasing maxKBlen. However, the numbers reported here used the current set of hyper-parameters and those should not be different.

Best,
Brian

**Comment by cyaaronk** [comment]
Dear author,

I am still unable to reproduce the paper's result after switching to whisper-large-v1.

I want to confirm the hyperparameters use for training as I suspect that is the problem.
So I see 2 different train files named "train.sh" and "train_large.sh", and each of them use a different set of hyper-parameters.

Notably, train.sh use:
    --biasinglist data/LibriSpeech/Blist/rareword_f15.txt \
    --dropentry 0.1 \
    --maxKBlen 200 \

But train_large.sh use:
    --biasinglist data/LibriSpeech/Blist/rareword_error.txt \
    --dropentry 0.3 \
    --maxKBlen 100 \


May I know which set of hyper-parameters are used to reproduce the result in HIGHLIGHTED lines?
![image](https://github.com/BriansIDP/WhisperBiasing/assets/22877783/b0a964ab-a61c-47b1-a3a6-ff9a2dcde440)

Thank you in advance.

**Comment by BriansIDP** [comment]
Hi. I used train_large.sh to get those results, but you could try both and see which one is better. Moreover, can you get the same number for Whisper large **without** TCPGen with my decoding code?

Thanks.

**Comment by cyaaronk** [comment]
-> can you get the same number for Whisper large without TCPGen with my decoding code?

I can't. By specifiying "--modeltype large-v1" in decoding.sh, I obtain WER 3.9%, which is below your reported WER 4.0%...

**Comment by BriansIDP** [comment]
This probably is because of the beam size. Another question is whether you can get the same result for whisper base.en? If so, then please adjust the drop rate to 0.1 and maxKBlen to 200 and try large v1 again.

**Comment by BriansIDP** [comment]
I just ran the experiments again and can get 3.5 WER after training for 9 epochs with exactly the same hyper-parameter setting. I do not have enough resource to run the full experiment, but I believe this setting in `train_large.sh` should be correct one I used. I am happy to provide the checkpoint at epoch 9 if you need it.

**Comment by cyaaronk** [comment]
May I have the below 3 files too? I want to compare and see if I generate the wrong files

data/LibriSpeech/train_clean_100_error.json
data/LibriSpeech/dev_error.json
data/LibriSpeech/Blist/rareword_error.txt

**Comment by BriansIDP** [comment]
[package.zip](https://github.com/BriansIDP/WhisperBiasing/files/14896285/package.zip)
Please find the uploaded package containing the 3 requested files.

**Comment by cyaaronk** [comment]
I am now using the exact same data files as provided in package.zip

I am also using the exact same hyperparameters as in train_large.sh, except I use "--modeltype large-v1":
python -u train.py \
    --modeltype large-v1 \
    --train_json package.zip/train_clean_100_error.json \
    --dev_json package.zip/dev_error.json \
    --lr 0.0005 \
    --batch_size 8 \
    --log_interval 200 \
    --nepochs 30 \
    --warmup_pct 0.0 \
    --decay_pct 0.2 \
    --expdir exp/${expdir} \
    --logfile exp/${expdir}/log.txt \
    --accumgrad 10 \
    --biasing \
    --biasinglist package.zip/rareword_error.txt \
    --dropentry 0.3 \
    --maxKBlen 100 \
    # --loadfrom exp/${expdir}/model.acc.best \

However, the training does not look good. I am a bit frustrated right now. I will continue to investigate the problem and see why my setup is not working...

My training log during the first epoch:
Start of training
200 / 3568 steps finished in 450.9030613899231 | Loss: 0.1914106047153473 | lr: 0.0005
400 / 3568 steps finished in 896.5303454399109 | Loss: 0.18273387640714644 | lr: 0.0005
600 / 3568 steps finished in 1342.7591316699982 | Loss: 0.18311550423502923 | lr: 0.0005
800 / 3568 steps finished in 1788.6015179157257 | Loss: 0.18367695815861226 | lr: 0.0005
1000 / 3568 steps finished in 2234.4437301158905 | Loss: 0.18201372645795344 | lr: 0.0005
1200 / 3568 steps finished in 2679.2384843826294 | Loss: 0.18427611894905568 | lr: 0.0005
1400 / 3568 steps finished in 3124.37246799469 | Loss: 0.18196221001446247 | lr: 0.0005
1600 / 3568 steps finished in 3570.4457457065582 | Loss: 0.1478701801225543 | lr: 0.0005
1800 / 3568 steps finished in 4017.830927848816 | Loss: 0.11629881415516138 | lr: 0.0005
2000 / 3568 steps finished in 4515.304264783859 | Loss: 0.11586045935750007 | lr: 0.0005
2200 / 3568 steps finished in 4961.234713554382 | Loss: 0.11627324216067791 | lr: 0.0005
2400 / 3568 steps finished in 5414.064345598221 | Loss: 0.11523292876780034 | lr: 0.0005
2600 / 3568 steps finished in 5867.573869228363 | Loss: 0.10959924660623073 | lr: 0.0005
2800 / 3568 steps finished in 6313.59872841835 | Loss: 0.11111329074949026 | lr: 0.0005
3000 / 3568 steps finished in 6761.316889286041 | Loss: 0.1087934809923172 | lr: 0.0005
3200 / 3568 steps finished in 7207.819852113724 | Loss: 0.11065450992435216 | lr: 0.0005
3400 / 3568 steps finished in 7656.039936542511 | Loss: 0.10922876708209514 | lr: 0.0005
50 out of 696 finished | time elapsed 8140.890429973602 | ACC: 0.7537674307823181
100 out of 696 finished | time elapsed 8249.231761217117 | ACC: 0.7537285685539246
150 out of 696 finished | time elapsed 8358.656593084335 | ACC: 0.7529393434524536
200 out of 696 finished | time elapsed 8466.749007940292 | ACC: 0.7520075440406799
250 out of 696 finished | time elapsed 8575.018678188324 | ACC: 0.7515411376953125
300 out of 696 finished | time elapsed 8684.038720846176 | ACC: 0.7507594227790833
350 out of 696 finished | time elapsed 8792.505848169327 | ACC: 0.7509676814079285
400 out of 696 finished | time elapsed 8900.716393470764 | ACC: 0.7508362531661987
450 out of 696 finished | time elapsed 9008.324385881424 | ACC: 0.7514156699180603
500 out of 696 finished | time elapsed 9116.564094543457 | ACC: 0.7516555786132812
550 out of 696 finished | time elapsed 9225.335455179214 | ACC: 0.7521702647209167
600 out of 696 finished | time elapsed 9333.376805067062 | ACC: 0.7516538500785828
650 out of 696 finished | time elapsed 9441.881403923035 | ACC: 0.7514838576316833
Total ACC: 0.7512460350990295

**Comment by BriansIDP** [comment]
Really sorry to hear that. The following is my log running exactly the same code:
```
200 / 3568 steps finished in 465.36361956596375 | Loss: 0.11080015506595373 | lr: 0.0005
400 / 3568 steps finished in 913.4314095973969 | Loss: 0.10208886802196503 | lr: 0.0005
600 / 3568 steps finished in 1357.271446466446 | Loss: 0.09423661444336176 | lr: 0.0005
800 / 3568 steps finished in 1799.925815820694 | Loss: 0.07171235047280788 | lr: 0.0005
1000 / 3568 steps finished in 2253.731970310211 | Loss: 0.0695452837832272 | lr: 0.0005
1200 / 3568 steps finished in 2714.914487838745 | Loss: 0.06755294295027853 | lr: 0.0005
1400 / 3568 steps finished in 3160.372603416443 | Loss: 0.06899610439315439 | lr: 0.0005
1600 / 3568 steps finished in 3605.412467479706 | Loss: 0.06779623856768012 | lr: 0.0005
1800 / 3568 steps finished in 4053.7230076789856 | Loss: 0.06722396709024907 | lr: 0.0005
2000 / 3568 steps finished in 4500.5759201049805 | Loss: 0.06820920614525676 | lr: 0.0005
2200 / 3568 steps finished in 4949.71203327179 | Loss: 0.06967545002698898 | lr: 0.0005
2400 / 3568 steps finished in 5399.286222457886 | Loss: 0.07014116352424025 | lr: 0.0005
2600 / 3568 steps finished in 5845.6132299900055 | Loss: 0.06619415694847702 | lr: 0.0005
2800 / 3568 steps finished in 6296.808760643005 | Loss: 0.06795134520158172 | lr: 0.0005
3000 / 3568 steps finished in 6746.229519367218 | Loss: 0.067449862472713 | lr: 0.0005
3200 / 3568 steps finished in 7193.022376060486 | Loss: 0.06842242132872343 | lr: 0.0005
3400 / 3568 steps finished in 7638.833619594574 | Loss: 0.06771309407427907 | lr: 0.0005
50 out of 696 finished | time elapsed 8123.8188354969025 | ACC: 0.8348023891448975
100 out of 696 finished | time elapsed 8232.904587507248 | ACC: 0.8331338763237
150 out of 696 finished | time elapsed 8341.361072063446 | ACC: 0.8333333134651184
200 out of 696 finished | time elapsed 8448.278109312057 | ACC: 0.8323795795440674
250 out of 696 finished | time elapsed 8556.081964969635 | ACC: 0.8322489857673645
300 out of 696 finished | time elapsed 8663.867151498795 | ACC: 0.8304839730262756
350 out of 696 finished | time elapsed 8771.22095155716 | ACC: 0.8304142355918884
400 out of 696 finished | time elapsed 8878.202127456665 | ACC: 0.8303437232971191
450 out of 696 finished | time elapsed 8985.846145629883 | ACC: 0.8312183618545532
500 out of 696 finished | time elapsed 9098.32931637764 | ACC: 0.83100825548172
550 out of 696 finished | time elapsed 9205.947943925858 | ACC: 0.8310040235519409
600 out of 696 finished | time elapsed 9313.576166629791 | ACC: 0.8303617238998413
650 out of 696 finished | time elapsed 9420.691895484924 | ACC: 0.8306593298912048
Total ACC: 0.8303753137588501
Saving best model at epoch 1
```

I am not sure how I can help more, but please feel free to drop any further questions you have here.

**Comment by cyaaronk** [comment]
Dear Author, 

Can you also share the initial whisper-large-v1 model you are using? 

Thank you in advance
